services:
  backend:
    build: ./backend
    container_name: fount_backend
    command: sh -c "python manage.py migrate && uvicorn backend.asgi:application --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/0
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TZ=Europe/Moscow

    networks:
      - fount-network
    develop:
      watch:
        - action: rebuild
          path: ./backend

  db:
    image: postgres:16-alpine
    container_name: fount_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Europe/Moscow
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fount-network

  redis:
    image: redis:7-alpine
    container_name: fount_redis
    networks:
      - fount-network
    environment:
      TZ: Europe/Moscow

networks:
  fount-network:
    driver: bridge

volumes:
  pgdata:
