name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # CI: Tests
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: fount
          POSTGRES_USER: fount
          POSTGRES_PASSWORD: fount
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U fount -d fount"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps (auth_service)
        run: pip install -r services/auth_service/requirements.txt

      - name: Run tests (auth_service)
        run: |
          cd services/auth_service
          python manage.py test
      - name: Install deps (likes_service)
        run: pip install -r services/likes_service/requirements.txt

      - name: Run tests (likes_service)
        run: |
          cd services/likes_service
          python manage.py migrate
          python manage.py test

      - name: Install deps (feedback_service)
        run: pip install -r services/feedback_service/requirements.txt

      - name: Run tests (feedback_service)
        run: |
          cd services/feedback_service
          python manage.py test

  # CI: docker build & push
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push auth_service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth_service:latest ./services/auth_service
          docker push ${{ secrets.DOCKER_USERNAME }}/auth_service:latest

      - name: Build & Push likes_service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/likes_service:latest ./services/likes_service
          docker push ${{ secrets.DOCKER_USERNAME }}/likes_service:latest

      - name: Build & Push feedback_service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/feedback_service:latest ./services/feedback_service
          docker push ${{ secrets.DOCKER_USERNAME }}/feedback_service:latest

      - name: Build & Push frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
